name: mimotion

on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main
    paths:
      - "mimotion.sh"
  watch:
    types: [started]

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2
        
      - name: mimotion
        env:
         PARAMETER: ${{ secrets.PARAMETER }}
        run: |
          sleep $(shuf -i 5-10 -n1)
          bash mimotion.sh $PARAMETER

      - name: delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 0
